const formOptions = {
  spellUpdater: {
    spellLevel: ["0", "1", "2", "3", "4", "5", "6", "7"],
    spellSchool: [
      "Abjuration",
      "Conjuration",
      "Divination",
      "Enchantment",
      "Evocation",
      "Illusion",
      "Necromancy",
      "Transmutation",
    ],
    spellAction: ["Action", "Bonus Action", "Ritual"],
    spellDamageType: [
      "Blugeoning",
      "Piercing",
      "Slashing",
      "Acid",
      "Cold",
      "Fire",
      "Force",
      "Lightning",
      "Necrotic",
      "Poison",
      "Psychic",
      "Radient",
      "Thunder",
      "Variable",
    ], // dependent on spell damage
    savingThrow: [
      "N/A",
      "Strength",
      "Dextarity",
      "Constitution",
      "Willpower",
      "Intelligence",
      "Charisma",
    ],
    spellRange: [
      "N/A",
      "Self",
      "Touch",
      "5 ft",
      "10 ft",
      "15 ft",
      "30 ft",
      "50 ft",
      "120 ft",
    ],
    spellRadius: ["N/A", "5ft", "10ft", "15ft", "30ft", "50ft", "120ft"],
    spellDuration: [
      "N/A",
      "1 round",
      "2 rounds",
      "5 rounds",
      "10 rounds",
      "over 1 minute",
    ],
    concentration: ["yes", "no"],
  },
  user: {},
  character: {
    chaLevel: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    chaClass: [
      "Barbarian",
      "Bard",
      "Cleric",
      "Druid",
      "Monk",
      "Ranger",
      "Rogue",
      "Paladin",
      "Sorcerer",
      "Wizard",
    ],
  },
};

export default formOptions;
